clientId="1030282721539-cqffujfjvsvhj6dnaaf68jsg3ptgabdk.apps.googleusercontent.com"
clientSecret="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"
[theme]
primaryColor="#33b5c6"
backgroundColor="#282a36"
secondaryBackgroundColor="#44475a"
textColor="#f8f8f2"
font="Monaco"
